# Copyright (c) 2024, Frappe Technologies and Contributors
# See license.txt

import ast
import json

import frappe
from frappe.tests.utils import FrappeTestCase

from helpdesk.api.settings.field_dependency import (
    add_function_to_script,
    generate_on_change_function,
    get_df_expression,
    get_field_dependency,
)
from helpdesk.test_utils import (
    DEFAULT_FIELD_DEPENDENCY_MAPPING,
    create_field_dependency,
)

DEPENDENCY_NAME = "Field Dependency-ticket_type-priority"
PARENT_FIELD = "ticket_type"
CHILD_FIELD = "priority"


class TestHDFormScript(FrappeTestCase):
    def setUp(self):
        # Set up any necessary test data or state
        create_field_dependency()
        pass

    def test_field_dependency_naming(self):
        # if we call this method, is the name of doc in the format "Field Dependency-{parent_field}-{child_field}"?
        dep_doc = frappe.get_list("HD Form Script", fields=["name", "is_standard"])[0]
        self.assertEqual(
            dep_doc.name,
            DEPENDENCY_NAME,
            f"Dependency name should be {DEPENDENCY_NAME}",
        )
        self.assertEqual(dep_doc.is_standard, 1)

    # test to check whether form customization is created or not
    def test_field_dependency_form_customization(self):

        # check if form customization is applied
        field = get_customized_form_field()
        self.assertEqual(field.depends_on, f"eval:doc.{PARENT_FIELD} != ''")
        self.assertEqual(
            field.mandatory_depends_on,
            f"eval:['Question', 'Bug'].includes(doc.{PARENT_FIELD})",
        )

    def test_field_dependency_enable_toggle(self):
        # If we disable a field dependency, does it remove the form customization?
        doc = frappe.get_doc("HD Form Script", DEPENDENCY_NAME)
        doc.enabled = 0
        doc.save()
        field = get_customized_form_field()
        self.assertIsNone(field.depends_on, "Depends on should be None when disabled")
        self.assertIsNone(
            field.mandatory_depends_on,
            "Mandatory depends on should be None when disabled",
        )

    def test_field_dependency_deletion(self):
        # If we delete a field dependency, does it remove the form customization?
        doc = frappe.get_doc("HD Form Script", DEPENDENCY_NAME)
        frappe.delete_doc("HD Form Script", doc.name)
        field = get_customized_form_field()
        self.assertIsNone(field.depends_on, "Depends on should be None after deletion")
        self.assertIsNone(
            field.mandatory_depends_on,
            "Mandatory depends on should be None after deletion",
        )

    def tearDown(self):
        frappe.db.delete(
            "HD Form Script", {"name": "Field Dependency-ticket_type-priority"}
        )
        pass


def get_customized_form_field():
    """
    Returns the customized form field for HD Ticket.
    """
    cf = frappe.get_doc("Customize Form")
    cf.doc_type = "HD Ticket"
    cf.fetch_to_customize()
    f = [f for f in cf.fields if f.fieldname == CHILD_FIELD]
    return f[0] if f else None


# Values that need escaping in a JavaScript string, and the trailer markers.
UNUSUAL_VALUES = [
    'Q"uote',
    "Back\\slash",
    "Line sep",
    "//FieldsCriteria: x",
    "//JSON: y",
]
TEST_PARENT = "ticket_type"
TEST_CHILD = "agent_group"
TEST_SCRIPT = f"Field Dependency-{TEST_PARENT}-{TEST_CHILD}"
SEEDED_SCRIPTS = [
    TEST_SCRIPT,
    "Field Dependency-ticket_type-customer",
    "Field Dependency-ticket_type-subject",
    "Field Dependency-ticket_type-contact",
    "Field Dependency-ticketXtype-agent_group",
]
INVALID_FIELD_PAIRS = [
    ("no_such_field", TEST_CHILD),
    (TEST_PARENT, "no_such_field"),
    ("subject", TEST_CHILD),
    (TEST_PARENT, "subject"),
    (TEST_PARENT, TEST_PARENT),
    ("ticket_type)", TEST_CHILD),
    (TEST_PARENT, "agent_group.x"),
    (TEST_PARENT, "agent group"),
]

# The script the generator wrote before values were JSON-encoded, for the
# default mapping with ticket type driving team. Plain names must still
# produce exactly this.
GOLDEN_SCRIPT = (
    "// This script is auto-generated by the Field Dependency feature. \n"
    "// It is not meant to be modified directly. \n"
    "\n"
    "function setupForm({doc, updateField, call, router, toast, $dialog, createToast ,applyFilters}) {\n"
    "\n"
    "    function update_agent_group(value){\n"
    '        if(value=="Unspecified") {\n'
    '            options = ["Urgent","High"]\n'
    '            applyFilters("agent_group",options)\n'
    "        }\n"
    "\n"
    '        else if(value=="Question") {\n'
    '            options = ["Medium","High"]\n'
    '            applyFilters("agent_group",options)\n'
    "        }\n"
    "\n"
    '        else if(value=="Bug") {\n'
    '            options = ["Medium"]\n'
    '            applyFilters("agent_group",options)\n'
    "        }\n"
    "\n"
    '        else if(value=="Incident") {\n'
    '            options = ["Urgent","High","Medium","Low"]\n'
    '            applyFilters("agent_group",options)\n'
    "        }\n"
    "\n"
    "        else {\n"
    '            applyFilters("agent_group",[])\n'
    "        }\n"
    "    }\n"
    "\n"
    "\n"
    "   return {\n"
    "        onChange: {\n"
    "            ticket_type: (newVal) => update_agent_group(newVal)\n"
    "        }\n"
    "    }\n"
    "    \n"
    "}\n"
    "// This JSON is to render the field dependency in the UI.\n"
    '//FieldsCriteria: "{}"\n'
    '//JSON: "{\\"Unspecified\\":[\\"Urgent\\",\\"High\\"],\\"Question\\":[\\"Medium\\",\\"High\\"],'
    '\\"Bug\\":[\\"Medium\\"],\\"Incident\\":[\\"Urgent\\",\\"High\\",\\"Medium\\",\\"Low\\"]}"\n'
)


def legacy_script(parent_field, child_field, mapping, fields_criteria):
    """The script as the generator wrote it before values were JSON-encoded:
    values were placed between double quotes as they were."""
    body = f"function update_{child_field}(value){{\n"
    first = True
    for parent, children in json.loads(mapping).items():
        options = ",".join([f'"{child}"' for child in children])
        body += f'        {"if" if first else "else if"}(value=="{parent}") {{\n'
        first = False
        body += f"            options = [{options}]\n"
        body += f'            applyFilters("{child_field}",options)\n'
        body += "        }\n\n"
    body += "        else {\n"
    body += f'            applyFilters("{child_field}",[])\n'
    body += "        }\n    }\n\n"
    script = "// This script is auto-generated by the Field Dependency feature. \n"
    script += "// It is not meant to be modified directly. \n\n"
    script += "function setupForm({doc, updateField, call, router, toast, $dialog, createToast ,applyFilters}) {\n\n"
    script += f"    {body}\n"
    script += f"""   return {{
        onChange: {{
            {parent_field}: (newVal) => update_{child_field}(newVal)
        }}
    }}
    """
    script += "\n}\n"
    script += "// This JSON is to render the field dependency in the UI.\n"
    script += "//FieldsCriteria: " + json.dumps(fields_criteria) + "\n"
    script += "//JSON: " + json.dumps(mapping) + "\n"
    return script


def script_body(script):
    return script.split("// This JSON is to render")[0]


class TestFieldDependencyScripts(FrappeTestCase):
    def setUp(self):
        frappe.set_user("Administrator")
        for name in UNUSUAL_VALUES:
            if not frappe.db.exists("HD Ticket Type", name):
                frappe.get_doc({"doctype": "HD Ticket Type", "name": name}).insert()

    def tearDown(self):
        frappe.set_user("Administrator")
        names = SEEDED_SCRIPTS + [
            f"Field Dependency-{parent}-{child}"
            for parent, child in INVALID_FIELD_PAIRS
        ]
        frappe.db.delete("HD Form Script", {"name": ["in", names]})
        for name in UNUSUAL_VALUES:
            frappe.db.delete("HD Ticket Type", {"name": name})
        frappe.db.delete(
            "Property Setter", {"doc_type": "HD Ticket", "field_name": TEST_CHILD}
        )
        frappe.clear_cache(doctype="HD Ticket")

    def test_values_are_written_as_json_strings(self):
        options = {
            UNUSUAL_VALUES[0]: [UNUSUAL_VALUES[1], UNUSUAL_VALUES[2]],
            UNUSUAL_VALUES[1]: [],
            UNUSUAL_VALUES[2]: [UNUSUAL_VALUES[0]],
            UNUSUAL_VALUES[3]: [UNUSUAL_VALUES[4], UNUSUAL_VALUES[3]],
            UNUSUAL_VALUES[4]: [UNUSUAL_VALUES[3]],
        }
        mapping = json.dumps(options)
        criteria = json.dumps(
            {
                "display": {
                    "enabled": False,
                    "value": [{"label": "//JSON: z", "value": "//JSON: z"}],
                },
                "mandatory": {"enabled": False, "value": []},
                "note": "//FieldsCriteria: n",
            }
        )
        create_field_dependency(TEST_PARENT, TEST_CHILD, mapping, criteria)

        script = frappe.db.get_value("HD Form Script", TEST_SCRIPT, "script")
        body = script_body(script)
        for parent, children in options.items():
            self.assertIn(f"if(value=={json.dumps(parent)})", body)
            listed = ",".join(json.dumps(child) for child in children)
            self.assertIn(f"options = [{listed}]\n", body)
        for value in UNUSUAL_VALUES:
            if json.dumps(value) != f'"{value}"':
                self.assertNotIn(f'"{value}"', body)
        self.assertNotIn(" ", script)

        saved = get_field_dependency(TEST_SCRIPT)
        self.assertEqual(saved.parent_field, TEST_PARENT)
        self.assertEqual(saved.child_field, TEST_CHILD)
        self.assertEqual(saved.parent_child_mapping, mapping)
        self.assertEqual(saved.fields_criteria, criteria)

    def test_plain_names_give_the_same_script_as_before(self):
        create_field_dependency(
            TEST_PARENT, TEST_CHILD, DEFAULT_FIELD_DEPENDENCY_MAPPING, "{}"
        )
        script = frappe.db.get_value("HD Form Script", TEST_SCRIPT, "script")
        self.assertEqual(script, GOLDEN_SCRIPT)
        self.assertEqual(
            script,
            legacy_script(
                TEST_PARENT, TEST_CHILD, DEFAULT_FIELD_DEPENDENCY_MAPPING, "{}"
            ),
        )

    def test_an_empty_child_list_is_kept(self):
        mapping = '{"Bug":[]}'
        create_field_dependency(TEST_PARENT, TEST_CHILD, mapping, "{}")
        script = frappe.db.get_value("HD Form Script", TEST_SCRIPT, "script")
        self.assertEqual(script, legacy_script(TEST_PARENT, TEST_CHILD, mapping, "{}"))

    def test_fields_must_be_link_or_select_fields_of_the_ticket(self):
        mapping = '{"Bug":["Medium"]}'
        for parent, child in INVALID_FIELD_PAIRS:
            with self.subTest(parent=parent, child=child):
                with self.assertRaises(frappe.ValidationError):
                    create_field_dependency(parent, child, mapping, "{}")
                self.assertFalse(
                    frappe.db.exists(
                        "HD Form Script", f"Field Dependency-{parent}-{child}"
                    )
                )

    def test_mapping_must_be_an_object_of_lists_of_names(self):
        for mapping in [
            "{}",
            "[]",
            '["Bug"]',
            '"Bug"',
            "null",
            "not json",
            '{"Bug": "Medium"}',
            '{"Bug": [1]}',
            '{"Bug": [null]}',
            '{"Bug": [["Medium"]]}',
            '{"Bug": {"Medium": 1}}',
        ]:
            with self.subTest(mapping=mapping):
                with self.assertRaises(frappe.ValidationError):
                    create_field_dependency(TEST_PARENT, TEST_CHILD, mapping, "{}")
                self.assertFalse(frappe.db.exists("HD Form Script", TEST_SCRIPT))

    def test_script_builders_check_the_fields(self):
        with self.assertRaises(frappe.ValidationError):
            generate_on_change_function({"Bug": []}, TEST_PARENT, "agent_group(1)")
        with self.assertRaises(frappe.ValidationError):
            add_function_to_script("ticket_type: 1, x", TEST_CHILD, "")
        with self.assertRaises(frappe.ValidationError):
            get_df_expression(
                "ticket_type) || (1",
                TEST_CHILD,
                {"enabled": True, "value": [{"label": "Any", "value": "Any"}]},
            )
        self.assertEqual(
            get_df_expression(
                TEST_PARENT,
                TEST_CHILD,
                {"enabled": True, "value": [{"label": "Bug", "value": "Bug"}]},
            ),
            "eval:['Bug'].includes(doc.ticket_type)",
        )

    def test_criteria_values_are_written_as_quoted_literals(self):
        # Each chosen value must stay one quoted string in the expression,
        # whatever characters its name has.
        prefix, suffix = "eval:", f".includes(doc.{TEST_PARENT})"
        names = UNUSUAL_VALUES + ["It's", "a\\'b", "']+['", "x\ny", "x\ry", "x\u2029y"]
        for value in names:
            with self.subTest(value=value):
                expression = get_df_expression(
                    TEST_PARENT,
                    TEST_CHILD,
                    {"enabled": True, "value": [{"label": value, "value": value}]},
                )
                self.assertTrue(expression.startswith(prefix))
                self.assertTrue(expression.endswith(suffix))
                listed = expression[len(prefix) : -len(suffix)]
                self.assertEqual(ast.literal_eval(listed), [value])
                for raw in ("\n", "\r", "\u2028", "\u2029"):
                    self.assertNotIn(raw, listed)

    def test_criteria_with_unusual_values_set_the_child_field_rules(self):
        criteria = {
            "display": {
                "enabled": True,
                "value": [{"label": v, "value": v} for v in UNUSUAL_VALUES],
            },
            "mandatory": {"enabled": False, "value": []},
        }
        create_field_dependency(
            TEST_PARENT,
            TEST_CHILD,
            json.dumps({UNUSUAL_VALUES[0]: []}),
            json.dumps(criteria),
        )
        depends_on = frappe.db.get_value(
            "Property Setter",
            {
                "doc_type": "HD Ticket",
                "field_name": TEST_CHILD,
                "property": "depends_on",
            },
            "value",
        )
        listed = depends_on[len("eval:") : -len(f".includes(doc.{TEST_PARENT})")]
        self.assertEqual(ast.literal_eval(listed), UNUSUAL_VALUES)

    def test_an_existing_dependency_is_found_by_its_exact_name(self):
        # "_" matches any character in a LIKE pattern.
        decoy = frappe.get_doc(
            {
                "doctype": "HD Form Script",
                "dt": "HD Ticket",
                "script": "// another script",
            }
        )
        decoy.name = "Field Dependency-ticketXtype-agent_group"
        decoy.insert()

        create_field_dependency(TEST_PARENT, TEST_CHILD, '{"Bug":["A"]}', "{}")
        create_field_dependency(TEST_PARENT, TEST_CHILD, '{"Bug":["B"]}', "{}")

        self.assertEqual(
            frappe.db.get_value("HD Form Script", decoy.name, "script"),
            "// another script",
        )
        self.assertEqual(
            frappe.db.count(
                "HD Form Script", {"name": ["like", "Field Dependency-%agent_group"]}
            ),
            2,
        )
        self.assertEqual(
            get_field_dependency(TEST_SCRIPT).parent_child_mapping, '{"Bug":["B"]}'
        )

    def test_enabling_a_script_without_criteria(self):
        script = legacy_script(TEST_PARENT, TEST_CHILD, '{"Bug":["A"]}', "{}")
        script = script.replace('//FieldsCriteria: "{}"\n', "")
        doc = insert_standard_script(TEST_SCRIPT, script, enabled=0)
        doc.enabled = 1
        doc.save()
        self.assertEqual(
            frappe.db.get_value("HD Form Script", TEST_SCRIPT, "enabled"), 1
        )
        self.assertIsNone(get_field_dependency(TEST_SCRIPT).fields_criteria)

    def test_patch_regenerates_old_scripts(self):
        from helpdesk.patches.regenerate_field_dependency_scripts import execute

        old_mapping = json.dumps({'Q"uote': ["A"], "Bug": ['Back\\slash"']})
        insert_standard_script(
            TEST_SCRIPT, legacy_script(TEST_PARENT, TEST_CHILD, old_mapping, "{}")
        )
        plain = "Field Dependency-ticket_type-customer"
        insert_standard_script(
            plain, legacy_script(TEST_PARENT, "customer", '{"Bug":["A"]}', "{}")
        )
        wrong_field = "Field Dependency-ticket_type-subject"
        insert_standard_script(
            wrong_field, legacy_script(TEST_PARENT, "subject", '{"Bug":["A"]}', "{}")
        )
        no_trailer = "Field Dependency-ticket_type-contact"
        insert_standard_script(no_trailer, "// written by hand\n")
        before = snapshot(SEEDED_SCRIPTS)

        execute()

        after = snapshot(SEEDED_SCRIPTS)
        script = after[TEST_SCRIPT]["script"]
        self.assertIn('if(value=="Q\\"uote")', script)
        self.assertIn('options = ["Back\\\\slash\\""]', script)
        self.assertNotIn('"Q"uote"', script_body(script))
        self.assertEqual(
            get_field_dependency(TEST_SCRIPT).parent_child_mapping, old_mapping
        )
        self.assertEqual(get_field_dependency(TEST_SCRIPT).fields_criteria, "{}")
        self.assertEqual(
            after[TEST_SCRIPT]["modified"], before[TEST_SCRIPT]["modified"]
        )
        self.assertEqual(after[TEST_SCRIPT]["enabled"], 1)
        self.assertEqual(after[plain], before[plain])
        for name in (wrong_field, no_trailer):
            self.assertEqual(after[name]["enabled"], 0)
            self.assertEqual(after[name]["script"], before[name]["script"])
            self.assertEqual(after[name]["modified"], before[name]["modified"])

        execute()
        self.assertEqual(snapshot(SEEDED_SCRIPTS), after)

    def test_patch_keeps_a_missing_criteria_line_readable(self):
        from helpdesk.patches.regenerate_field_dependency_scripts import execute

        script = legacy_script(TEST_PARENT, TEST_CHILD, '{"Bug":["A"]}', "{}")
        insert_standard_script(
            TEST_SCRIPT, script.replace('//FieldsCriteria: "{}"\n', "")
        )
        execute()
        saved = get_field_dependency(TEST_SCRIPT)
        self.assertEqual(saved.enabled, 1)
        self.assertIsNone(saved.fields_criteria)
        self.assertEqual(saved.parent_child_mapping, '{"Bug":["A"]}')
        after = snapshot([TEST_SCRIPT])
        execute()
        self.assertEqual(snapshot([TEST_SCRIPT]), after)

    def test_only_system_managers_change_form_scripts(self):
        path = frappe.get_app_path(
            "helpdesk", "helpdesk", "doctype", "hd_form_script", "hd_form_script.json"
        )
        perms = {p["role"]: p for p in frappe.get_file_json(path)["permissions"]}
        granted = {k for k, v in perms["Agent Manager"].items() if k != "role" and v}
        self.assertEqual(
            granted, {"read", "select", "report", "export", "print", "email"}
        )
        for right in ("create", "write", "delete", "share"):
            self.assertEqual(perms["System Manager"].get(right), 1)
        self.assertEqual(perms["HD Customer"], {"read": 1, "role": "HD Customer"})


def insert_standard_script(name, script, enabled=1):
    doc = frappe.get_doc(
        {
            "doctype": "HD Form Script",
            "dt": "HD Ticket",
            "script": script,
            "enabled": enabled,
            "is_standard": 1,
            "apply_on_new_page": 1,
        }
    )
    doc.name = name
    return doc.insert()


def snapshot(names):
    return {
        d.name: {"script": d.script, "enabled": d.enabled, "modified": d.modified}
        for d in frappe.get_all(
            "HD Form Script",
            filters={"name": ["in", names]},
            fields=["name", "script", "enabled", "modified"],
        )
    }
